// <auto-generated />
using Aiursoft.Observer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Aiursoft.Observer.Migrations
{
    [DbContext(typeof(StatusDbContext))]
    [Migration("20191005082735_AddMonitorRule")]
    partial class AddMonitorRule
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Aiursoft.Observer.Models.MonitorRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CheckAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpectedContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LastHealthStatus")
                        .HasColumnType("bit");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MonitorRules");
                });
#pragma warning restore 612, 618
        }
    }
}
