// <auto-generated />
using Aiursoft.Stargate.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Aiursoft.Stargate.Migrations
{
    [DbContext(typeof(StargateDbContext))]
    [Migration("20180210102759_MigratedToSQLServer")]
    partial class MigratedToSQLServer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Aiursoft.Pylon.Models.Stargate.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AppId");

                    b.Property<string>("ConnectKey");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Description");

                    b.Property<TimeSpan>("LifeTime");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("Aiursoft.Pylon.Models.Stargate.StargateApp", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Apps");
                });

            modelBuilder.Entity("Aiursoft.Pylon.Models.Stargate.Channel", b =>
                {
                    b.HasOne("Aiursoft.Pylon.Models.Stargate.StargateApp", "App")
                        .WithMany("Channels")
                        .HasForeignKey("AppId");
                });
#pragma warning restore 612, 618
        }
    }
}
