// <auto-generated />
using System;
using Aiursoft.Stargate.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Aiursoft.Stargate.Migrations
{
    [DbContext(typeof(StargateDbContext))]
    [Migration("20190315031416_AddLifeTime")]
    partial class AddLifeTime
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Aiursoft.Pylon.Models.Stargate.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AppId");

                    b.Property<string>("ConnectKey");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Description");

                    b.Property<double>("LifeTime");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("Aiursoft.Pylon.Models.Stargate.StargateApp", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Apps");
                });

            modelBuilder.Entity("Aiursoft.Pylon.Models.Stargate.Channel", b =>
                {
                    b.HasOne("Aiursoft.Pylon.Models.Stargate.StargateApp", "App")
                        .WithMany("Channels")
                        .HasForeignKey("AppId");
                });
#pragma warning restore 612, 618
        }
    }
}
