// <auto-generated />
using System;
using Aiursoft.Stargate.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Aiursoft.Stargate.Migrations
{
    [DbContext(typeof(StargateDbContext))]
    partial class StargateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Aiursoft.Pylon.Models.Stargate.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AppId");

                    b.Property<string>("ConnectKey");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Description");

                    b.Property<TimeSpan>("LifeTime");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("Aiursoft.Pylon.Models.Stargate.StargateApp", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Apps");
                });

            modelBuilder.Entity("Aiursoft.Pylon.Models.Stargate.Channel", b =>
                {
                    b.HasOne("Aiursoft.Pylon.Models.Stargate.StargateApp", "App")
                        .WithMany("Channels")
                        .HasForeignKey("AppId");
                });
#pragma warning restore 612, 618
        }
    }
}
