// <auto-generated />
using Aiursoft.Status.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using System;

namespace Aiursoft.Status.Migrations
{
    [DbContext(typeof(StatusDbContext))]
    [Migration("20191214175009_AddPath")]
    partial class AddPath
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Aiursoft.Pylon.Models.Status.ErrorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AppId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EventLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("LogTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("Aiursoft.Pylon.Models.Status.StatusApp", b =>
                {
                    b.Property<string>("AppId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AppId");

                    b.ToTable("StatusApps");
                });

            modelBuilder.Entity("Aiursoft.Status.Models.MonitorRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CheckAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpectedContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastCheckTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LastHealthStatus")
                        .HasColumnType("bit");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MonitorRules");
                });

            modelBuilder.Entity("Aiursoft.Pylon.Models.Status.ErrorLog", b =>
                {
                    b.HasOne("Aiursoft.Pylon.Models.Status.StatusApp", "Context")
                        .WithMany("ErrorLogs")
                        .HasForeignKey("AppId");
                });
#pragma warning restore 612, 618
        }
    }
}
