// <auto-generated />
using System;
using Aiursoft.Status.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Aiursoft.Status.Migrations
{
    [DbContext(typeof(StatusDbContext))]
    partial class StatusDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Aiursoft.Status.Models.MonitorRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CheckAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpectedContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastCheckTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LastHealthStatus")
                        .HasColumnType("bit");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MonitorRules");
                });
#pragma warning restore 612, 618
        }
    }
}
