// <auto-generated />
using System;
using Aiursoft.Warpgate.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Aiursoft.Warpgate.Migrations
{
    [DbContext(typeof(WarpgateDbContext))]
    [Migration("20210528160209_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Aiursoft.Warpgate.SDK.Models.WarpRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AppId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("RecordUniqueName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("RecordUniqueName")
                        .IsUnique()
                        .HasFilter("[RecordUniqueName] IS NOT NULL");

                    b.ToTable("Records");
                });

            modelBuilder.Entity("Aiursoft.Warpgate.SDK.Models.WarpgateApp", b =>
                {
                    b.Property<string>("AppId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AppId");

                    b.ToTable("WarpApps");
                });

            modelBuilder.Entity("Aiursoft.Warpgate.SDK.Models.WarpRecord", b =>
                {
                    b.HasOne("Aiursoft.Warpgate.SDK.Models.WarpgateApp", "App")
                        .WithMany("WarpRecords")
                        .HasForeignKey("AppId");

                    b.Navigation("App");
                });

            modelBuilder.Entity("Aiursoft.Warpgate.SDK.Models.WarpgateApp", b =>
                {
                    b.Navigation("WarpRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
